[environments.development]
store = "jcs-blueprint"
theme = "167272350033"

[environments.staging]
store = "jcs-blueprint"
theme = "167272350033"
ignore = ["templates/*", "config/*"]

[environments.production]
store = "jcs-blueprint"
theme = "167272350033"
ignore = ["templates/*", "config/*"]
