[environments.development]
store = "jcs-blueprint"
theme = "167220773201"

[environments.staging]
store = "jcs-blueprint"
theme = "167220773201"
ignore = ["templates/*", "config/*"]

[environments.production]
store = "jcs-blueprint"
theme = "167220773201"
ignore = ["templates/*", "config/*"]
